name: complexespp CI
on: 
  push:
   branches: 
     - main
  pull_request:
   branches: 
     - main
jobs:
   tests:
    runs-on: ubuntu-latest
    name: complexes build and test
    defaults:
      run:
        working-directory: ./complexes++
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake libyaml-cpp-dev
      - name: configure
        run: |
          mkdir build && cd build
          cmake ..
      - name: build
        run: |
          cd build
          make
