name: Pycomplexes CI
on: 
  push:
   branches: 
     - main
  pull_request:
   branches: 
     - main
jobs:
   tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pycomplexes
    strategy:
      matrix:
        python-version: ["3.x"]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install Dependencies
        run: |
          sudo apt-get install -y wget bzip2
          pip install --upgrade pytest pyyaml MDAnalysis tqdm numba pandas six
      - name: install library
        run: |
          pip install -e .
      - name: Run test suite
        run: |
          pytest -v
